locations:
    nofib_config_dir_path: ..\nofib\mk
    nofib_exec_path: ../nofib
    nofib_logs_dir: ..\nofib\logs
    nofib_analysis_dir: ../nofib/analysis
    nofib_analysis_exec: ..\nofib\nofib-analyse
    nofib_exec_path_PO: ../../ghc/nofib
    nofib_logs_dir_PO: ..\..\ghc\nofib\logs
    nofib_analysis_dir_PO: ../../ghc/nofib/analysis
    nofib_analysis_exec_PO: ..\..\ghc\nofib\nofib-analyse
    log_location: PythonLogs
    optimal_presets: ..\optimal_presets
    phase_order_file: ../../../phase.txt
settings:
    nofib_runs: 175 # DEFAULT 30
    flags: [-fcall-arity,-fcase-merge,-fcmm-elim-common-blocks,-fcmm-sink,-fcpr-anal,-fcse,
            -fdicts-cheap,-fdicts-strict,-fdmd-tx-dict-sel,-fdo-eta-reduction,-fdo-lambda-eta-expansion,
            -feager-blackholing,-fenable-rewrite-rules,-fexcess-precision,-fexpose-all-unfoldings,
            -ffloat-in,-ffull-laziness,-ffun-to-thunk,-fignore-asserts,-fignore-interface-pragmas,
            -flate-dmd-anal,-fliberate-case,-fliberate-case-threshold=2000,-floopification,-fmax-inline-alloc-size=128,
            -fmax-inline-memcpy-insns=32,-fmax-inline-memset-insns=32,-fmax-relevant-binds=6,-fmax-simplifier-iterations=4,
            -fmax-worker-args=10,-fno-opt-coercion,-fno-pre-inlining,-fno-state-hack,-fomit-interface-pragmas,-fomit-yields,
            -foptimal-applicative-do,-fpedantic-bottoms,-fregs-graph,-fregs-iterative,-fsimplifier-phases=2,-fsimpl-tick-factor=100,
            -fspec-constr,-fspec-constr-count=3,-fspec-constr-threshold=2000,-fspecialise,-fcross-module-specialise,-fstatic-argument-transformation,
            -fstrictness,-fstrictness-before=1,-funbox-small-strict-fields,-funbox-strict-fields,-funfolding-creation-threshold=750,
            -funfolding-dict-discount=30,-funfolding-fun-discount=60,-funfolding-keeness-factor=1.5,-funfolding-use-threshold=60,
            -fvectorisation-avoidance,-fvectorise,-fworker-wrapper] # 59 items
    ghc-default-flags: [-O0,-O1,-O2,-Os]
    multicore_cores: 4
    log_output_loc: logs/
    num_of_optimizer_runs: 1
    run_allowance: 10000
iterative_settings:
    num_of_presets: 300 # DEFAULT 300
genetic_settings: # FOGA Paper
    max_iterations: 120 # 2 DEFAULT 100
    population_size: 150 # 40 DEFAULT 277
    mutation_prob: 0.287
    elitism_ratio: 0.147
    crossover_prob: 0.120
    crossover_type: segment
    num_of_segments: 3 # Change later?
    mutation_type: guass_by_center
    selection_type: linear_ranking
    max_iter_without_improvement: 48 # Default 45
boca_settings:
    initial_set: 50 # 40 100
    num_of_impactful_optimizations: 6 # 10
    iterations: 4000 # 50 100
    max_without_improvement: 1000
    decay: 0.74 # 0.5
    offset: 50 # 20
    scale: 30 # 10
